version: '3'
services:
  app:
    build:
      context: .
      target: dev
    command: air -c .air.toml
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0.29
    # platform: linux/amd64
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practice_todo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
volumes:
  db-data: